
const items = [
  {
    id: '001',
    image: './myntra img/men-1.webp',
    company: 'Carlton London',
    item_name: 'Rhodium-Plated CZ T shirt',
    original_price: 1045,
    current_price: 606,
    discount_percentage: 42,
      return_period: 14,
      delivery_date: '10 Oct 2023',
      rating: {
          stars: 4.5,
          count: 1400,
      },
  },
  {
      id: '002',
      image:  './myntra img/men-3.webp',
      company: 'Carlton London',
      item_name: 'pure cotton oversized T shirt',
      original_price: 599,
      current_price: 999,
      discount_percentage: 45,
      return_period: 14,
      delivery_date: '10 Oct 2023',
      rating: {
          stars: 4.3,
          count: 24,
      },
  },
  {
      id: '003',
      image: './myntra img/men-4.webp',
      company: 'H&M',
      item_name: 'Print slim T-shirt',
      original_price: 1599,
      current_price: 495,
      discount_percentage: 69,
      return_period: 14,
      delivery_date: '10 Oct 2024',
      rating: {
          stars: 4.1,
          count: 249,
      },
  },
  {
      id: '004',
      image: './myntra img/men-5.webp',
      company:'HRX by hritik Roshan',
      item_name :'Rapid Dry Trainning T-shirt',
      original_price: 309,
      current_price: 699,
      discount_percentage: 56,
      return_period: 14,
      delivery_date: '10 Oct 2024',
      rating: {
          stars: 3.0,
          count: 786,
      },
  },
  {
    id:'005',
    image : './myntra img/women-1.webp',
    company: 'DressBerry',
    item_name :'bloomin freshed tailored Top',
      original_price: 899,
      current_price: 1489,
      discount_percentage: 60,
      return_period: 14,
      delivery_date: '10 Oct 2024',
      rating: {
          stars: 4.2,
          count: 3500,
      },
  },
  {
      id: '006',
      image : './myntra img/women-2.webp',
      company: 'stylecast xSlyck',
      item_name :'Polka dot puff sleeve Top',
      original_price: 995,
      current_price: 995,
      discount_percentage: 0,
      return_period: 14,
      delivery_date: '10 Oct 2024',
      rating: {
          stars: 0.0,
          count: 0,
      },
  },
  {
    id:'007',
    image : './myntra img/women-3.webp',
    company: 'chemistry',
    item_name :'cut out pintucks Top',
      original_price: 1599,
      current_price: 639,
      discount_percentage: 60,
      rating: {
          stars: 4.2,
          count: 388,
      },
  },
  {
    id:'008',
    image : './myntra img/women-5.webp',
    company: 'ALL ABOUT YOU',
    item_name :'Floral print Top',
      original_price: 285,
      current_price: 142,
      discount_percentage: 50,
      return_period: 14,
      delivery_date: '10 Oct 2023',
      rating: {
          stars: 4.2,
          count: 5200,
      },
  }
];
